### ISSUE TITLE
SVG importing issues with gradient polygons

### ISSUE THREAD

**Issue by SaeedMasoumi** [2d-inc/support#194]
I tried to import this SVG file into Flare, but some polygons didn't import correctly.
original SVG:
<img width="509" alt="screen shot 2018-12-30 at 2 03 31 pm" src="https://user-images.githubusercontent.com/6934577/50546363-ee2c5f80-0c3b-11e9-9c8b-bec8978692a3.png">
In Flare, after import:
<img width="507" alt="screen shot 2018-12-30 at 2 04 12 pm" src="https://user-images.githubusercontent.com/6934577/50546369-043a2000-0c3c-11e9-9d7b-69799315466a.png">

[iceberg.svg.zip](https://github.com/2d-inc/support/files/2717065/iceberg.svg.zip)

**Comment by luigi-rosso** [comment]
There were a couple issue with this. We weren't linking referenced fills in styles and we weren't handling gradients with userSpaceOnUse as the gradientUnits. Both of these have been addressed, I'll post here when the fix is available on 2dimensions.com.

![screen shot 2019-01-03 at 8 08 20 pm](https://user-images.githubusercontent.com/454182/50673547-64f68f00-0f93-11e9-8d0f-08cb6f6198de.png)
