### ISSUE TITLE
Cannot open project anymore after adding a mask to an image

### ISSUE THREAD

**Issue by erabti** [2d-inc/support#276]
After I have deleted an old image from my assets (the image is still in the project) I added another image and the moment I tried to add a mask to the new image a crash occurred and now I cannot enter to my project.

This is very critical. I have zero access now.

https://rive.app/a/erabti2/files/flare/lang-switcher

**Comment by tsinis** [comment]
> After I have deleted an old image from my assets (the image is still in the project) I added another image and the moment I tried to add a mask to the new image a crash occurred and now I cannot enter to my project.
> 
> 
> 
> This is very critical. I have zero access now.
> 
> 
> 
> https://rive.app/a/erabti2/files/flare/lang-switcher


Hey @erabti! Sorry to hear that. When something like this happens to me — I'm just rolling back with Revision History. Try it out:

https://docs.rive.app/rive/revision-history

Hope it helps!

**Comment by erabti** [comment]
@luigi-rosso What shall I do?

**Comment by luigi-rosso** [comment]
Hi @erabti, I temporarily applied a fix that'll let you open the file again.

The issue was that the object used as the mask was a parent of the content. This was causing a recursive dependency when drawing the mask. We'll shortly introduce a fix that will prevent a designer from accidentally doing this, but in the meantime try not to select a parent object as the mask or it'll happen again. 

I'll post a note when the fix goes up, in the meantime you should be unblocked!

Thanks for bringing this to my attention and sorry for the woes!

Luigi

**Comment by luigi-rosso** [comment]
Btw, specifically, in your file the US Flag Image was masked by the Notch node which was a parent of the US Flag. I just removed that mask. I suggest making a separate object to use as the mask or pick a child of Notch (not US Flag) as the masking source.

**Comment by luigi-rosso** [comment]
The fix is up on rive.app which will prevent you from accidentally getting into this situation again. Thanks again. Feel free to re-open if this is still giving you trouble.
